"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


SECRET_KEY = (
    'django-insecure-a$pveik%z27c60@5xaa32(iw)'
    '*8qt%y1o&(!ha&!k#_4(#ud38'
)

DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'accounts',
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'


# =========================
# EMAIL / GMAIL SMTP
# =========================

MAILERS = {
    "default": {
        "BACKEND":
            "django.core.mail.backends.smtp.EmailBackend",

        "OPTIONS": {
            "host":
                "smtp.gmail.com",

            "port":
                587,

            "username":
                os.getenv(
                    "GMAIL_USER"
                ),

            "password":
                os.getenv(
                    "GMAIL_APP_PASSWORD"
                ),

            "use_tls":
                True,
        },
    },
}


DEFAULT_FROM_EMAIL = os.getenv(
    "GMAIL_USER"
)


# =========================
# VERIFICACIÓN DE CORREO
# =========================

EMAIL_VERIFICATION_TIMEOUT = (
    60 * 60 * 24
)


# =========================
# RECUPERACIÓN CONTRASEÑA
# =========================

# El token de recuperación es válido durante 24 horas.
PASSWORD_RESET_TIMEOUT = (
    60 * 60 * 24
)


PASSWORD_RESET_FRONTEND_URL = os.getenv(
    "PASSWORD_RESET_FRONTEND_URL",
    "http://localhost:55000/reset-password",
)


AUTH_USER_MODEL = 'accounts.User'


CORS_ALLOW_ALL_ORIGINS = True